name: Build

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        python-version:
        - 3.5
        - 3.6
        - 3.7
        - 3.8

    runs-on: ${{matrix.os}}

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Run tests
      run: python3 _runner_tests.py
      working-directory: ./python3
